services:
  nntp-server:
    hostname: nntp-server
    build:
      dockerfile: Dockerfile-nntp
    networks:
      my_network:
        ipv4_address: 172.21.0.2
    ports:
      - 1119:119
    post_start:
      - command:  sh -c "/usr/local/bin/wait_for_tcp.sh 119 20 && /usr/local/bin/preseed.sh"

  fastapi-server:
    image: fastapi
    hostname: fastapi-server
    volumes:
      - ./server:/app/server:rw
      - ./static:/app/static:rw
      - ./templates:/app/templates:rw
    build:
      dockerfile: Dockerfile-api
      args:
        INN_SERVER_NAME: nntp-server
    networks:
      my_network:
        ipv4_address: 172.21.0.3
    ports:
      - 5001:8000
    depends_on:
      - nntp-server

  imls-react:
    image: imlsreact
    build:
      dockerfile: Dockerfile-fe
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: 'http://fastapi-server:5001'
    networks:
      my_network:
        ipv4_address: 172.21.0.4
    ports:
      - 4000:80
    depends_on:
      - fastapi-server

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1   # This is crucial for the nntp config to work.
