FROM debian:stable

RUN apt-get update && apt-get install --yes --no-install-recommends inn2 j2cli netcat-traditional openssl tini

COPY ./server_config/news_server/docker-entrypoint.sh /docker-entrypoint.sh
COPY ./server_config/news_server/templatize.sh /templatize.sh
COPY ./server_config/news_server/j2_filters.py /j2_filters.py
COPY ./server_config/news_server/etc/news/* /etc/news/
COPY ./config.json /config.json
RUN /templatize.sh /j2_filters.py /etc/news /config.json


RUN chown root:root /etc/news -R

COPY ./server_config/news_server/var/lib/news/newsusers.j2 /var/lib/news/newsusers.j2
RUN /templatize.sh /j2_filters.py /var/lib/news/ /config.json

RUN chown root:root /var/lib/news/newsusers

RUN mkdir -p /var/www/inn
RUN chown news:news /var/www/inn

COPY ./server_config/news_server/wait_for_tcp.sh /usr/local/bin/

COPY ./server_config/news_server/preseed.sh.j2 /usr/local/bin/
RUN /templatize.sh /j2_filters.py /usr/local/bin/ /config.json
RUN chmod a+x /usr/local/bin/preeseed.sh

RUN rm /config.json

EXPOSE 119
# ENTRYPOINT ["/usr/bin/tini", "--"]

ENTRYPOINT ["/docker-entrypoint.sh", "-d"]
