FROM debian:stable

RUN apt-get update && apt-get install --yes --no-install-recommends inn2 j2cli netcat-traditional openssl tini

COPY ./server_config/news_server/docker-entrypoint.sh /docker-entrypoint.sh

COPY ./tools/docker_tools/j2_related/templatize.sh /tmp/templatize.sh
COPY ./tools/docker_tools/j2_related/j2_filters.py /tmp/j2_filters.py
COPY ./config.json /tmp/config.json

COPY ./server_config/news_server/etc/news/* /etc/news/
RUN /tmp/templatize.sh /tmp/j2_filters.py /etc/news /tmp/config.json


RUN chown root:root /etc/news -R

COPY ./server_config/news_server/var/lib/news/newsusers.j2 /var/lib/news/newsusers.j2
RUN /tmp/templatize.sh /tmp/j2_filters.py /var/lib/news/ /tmp/config.json

RUN chown root:root /var/lib/news/newsusers

RUN mkdir -p /var/www/inn
RUN chown news:news /var/www/inn

COPY ./server_config/news_server/wait_for_tcp.sh /usr/local/bin/

COPY ./server_config/news_server/preseed.sh.j2 /usr/local/bin/
RUN /tmp/templatize.sh /tmp/j2_filters.py /usr/local/bin /tmp/config.json

RUN chmod a+x /usr/local/bin/preseed.sh

RUN rm /tmp/config.json

EXPOSE 119
# ENTRYPOINT ["/usr/bin/tini", "--"]

ENTRYPOINT ["/docker-entrypoint.sh", "-d"]
