#!/usr/bin/env -S uv run --script

# Source: https://api.ies.ed.gov/eric?search=python
# Docs: https://eric.ed.gov/?api#/default/get_eric_

# /// script
# requires-python = ">=3.13"
# dependencies = [
#     "httpx",
#     "pydantic",
# ]
# ///
#
# Generated with command:
# uv tool run --from=datamodel-code-generator datamodel-codegen \
#             --input ERIC-open-records.json --input-file-type json \
#             --output eric_models.py
#
# # generated by datamodel-codegen:
#   filename:  ERIC-open-records.json
#   timestamp: 2025-05-11T10:03:25+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class ModelItem(BaseModel):
    id: str
    pdf_url: str = Field(..., alias="pdf-url")
    title: str
    description: str
    e_fulltextauth: str
    source: str
    publicationdateyear: str
    abstractor: str
    peerreviewed: str
    e_yearadded: str
    iesfunded: str
    e_datemodified: str
    publisher: str
    ieslinkpublication: str
    url: str
    sourceid: str
    ieswwcreviewed: str
    ieslinkwwcreviewguide: str
    ieslinkdatasource: str
    subject: str
    author: str
    authorxlink: str
    educationlevel: str
    publicationtype: str
    iesgrantcontractnum: str
    iesgrantcontractnumxlink: str
    language: str
    institution: str
    identifiersgeo: str
    sponsor: str
    identifierstest: str
    issn: str
    iescited: str
    identifierslaw: str
    audience: str
    isbn: str


class Model(BaseModel):
    __root__: list[ModelItem]
