# generated by datamodel-codegen:
#   filename:  eric_item.json
#   timestamp: 2025-04-11T09:38:56+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    id: str
    title: str
    author: list[str]
    description: str
    subject: list[str]
    publicationtype: list[str]
    publicationdateyear: int
    language: list[str]
    issn: list[str]
    publisher: str
    peerreviewed: str
