#!/usr/bin/env -S uv run --script

# Source: https://qubeshub.org/oaipmh/?verb=ListRecords&metadataPrefix=oai_dc&set=publications
# Docs: https://qubeshub.org/oaipmh/

# /// script
# requires-python = ">=3.13"
# dependencies = [
#     "httpx",
#     "pydantic",
# ]
# ///

"""
Bulk-import publication metadata from QUBES Hub via the OAI-PMH API.

QUBES Hub exposes an OAI-PMH (Open Archives Initiative Protocol for Metadata
Harvesting) endpoint.  This module reads from the locally cached
``qubes_records.json`` file (generated by ``convert_qubes_xml_to_json.py``)
and translates each record into a standardised OME ``EducationResource`` card.
"""

import json
import logging
from collections.abc import Iterator
from pathlib import Path

from pydantic import ValidationError

from server.plugins.ome_plugin import EducationResource
from server.plugins.qubes.plugin import QubesPlugin
from server.plugins.qubes.qubes_models import Model, ModelItem

QUBES_OAI_URL = (
    "https://qubeshub.org/oaipmh/"
    "?verb=ListRecords&metadataPrefix=oai_dc&set=publications"
)
QUBES_BASE_URL = "https://qubeshub.org"

logger = logging.getLogger(__name__)

plugin = QubesPlugin()


def _parse_records(items: list) -> list[ModelItem]:
    """
    Validate raw record dicts into :class:`ModelItem` objects.

    Uses a Python 3.13+ ExceptionGroup to collect all validation errors
    and report them together while returning valid records to the caller.
    """
    records: list[ModelItem] = []
    errors: list[ValidationError] = []
    for item in items:
        try:
            records.append(ModelItem.model_validate(item))
        except ValidationError as exc:
            errors.append(exc)
    if errors:
        msg = f"Skipping {len(errors)} malformed QUBES record(s)"
        try:
            raise ExceptionGroup(msg, errors)
        except* ValidationError as eg:
            for exc in eg.exceptions:
                logger.warning("Malformed QUBES record: %s", exc)
    return records


def bulk_translate(records: list[dict]) -> Iterator[EducationResource]:
    """Translate raw QUBES record dicts to OME EducationResource cards."""
    yield from (plugin.make_metadata_card_from_json(json.dumps(r)) for r in records)


def bulk_import(
    cache_path: Path | None = None,
) -> list[dict]:
    """
    Load QUBES records from the local cache and return serialised OME records.

    The cache file ``qubes_records.json`` is generated by
    ``convert_qubes_xml_to_json.py`` from the OAI-PMH XML export.  Run that
    script first if the cache does not yet exist.

    Args:
        cache_path: Path to ``qubes_records.json``.  If ``None``, defaults
                    to the file next to this module.

    Returns:
        A list of serialised :class:`EducationResource` dicts.

    Raises:
        FileNotFoundError: If ``qubes_records.json`` does not exist.
    """
    if cache_path is None:
        cache_path = Path(__file__).resolve().parent / "qubes_records.json"

    if not cache_path.exists():
        msg = (
            f"{cache_path.name} not found. "
            "Run convert_qubes_xml_to_json.py to generate it from qubes_records.xml."
        )
        raise FileNotFoundError(msg)

    raw = json.loads(cache_path.read_text())
    records = Model.model_validate(raw).root
    return [
        card.model_dump() for card in bulk_translate([r.model_dump() for r in records])
    ]


if __name__ == "__main__":
    here = Path(__file__).resolve().parent

    print("=== QUBES Hub publications ===")
    results = bulk_import(cache_path=here / "qubes_records.json")
    print(f"Found {len(results)} records")
    for card in results:
        print(f"  {card['title']!r}  (authors: {card['authors'][:2]})")
