name: sphinx

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Or manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv python install  # Version from pyproject.toml project.requires-python
      # - run: uv add --editable ".[docs]"
      - uses: actions/configure-pages@v5
      # - run: sphinx-apidoc -f -o docs src  # Todo: Add demo code
      # - run: shopt -s globstar && rst2myst convert docs/**/*.rst
      - run: uv sync --group docs
      - run: uv run sphinx-build -c docs . docs/_build/html
      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs/_build/html
      - run: echo ${{ github.event_name }}

  deploy_docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.event_name != 'pull_request'
    needs: build_docs
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event_name }}
      - uses: actions/deploy-pages@v4
        id: deployment
